# Generated by Django 6.0.2 on 2026-04-04 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
