# Generated by Django 6.0.2 on 2026-04-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_delete_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, help_text='In kilometers/miles, for vehicles only', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
