# Generated by Django 6.0.2 on 2026-04-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_boost_start_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_tags',
            field=models.TextField(blank=True, help_text='Search keywords separated by commas (e.g. iphone, apple, smartphone)', null=True),
        ),
    ]
