# Generated by Django 6.0.2 on 2026-04-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_search_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('New', 'New')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, help_text='In kilometres/miles, for vehicles only', null=True),
        ),
    ]
