# Generated by Django 6.0.2 on 2026-04-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_condition_alter_product_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('Good', 'Good'), ('Standerd', 'Standerd'), ('Bad', 'Bad')], max_length=10),
        ),
    ]
