# Generated by Django 6.0.2 on 2026-04-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_phonenumberrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='negotiated_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
