# Generated by Django 6.0.2 on 2026-04-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='category_icons/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('mobiles', 'Mobiles'), ('laptops', 'Laptops'), ('fashion', 'Fashion'), ('camera', 'Camera'), ('home', 'Home'), ('cars', 'Cars'), ('gaming', 'Gaming'), ('audio', 'Audio'), ('bikes', 'Bikes'), ('watch', 'Watch'), ('books', 'Books')], max_length=100),
        ),
    ]
