# Generated by Django 6.0.2 on 2026-04-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_seed_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('mobiles', 'Mobiles'), ('laptops', 'Laptops'), ('fashion', 'Fashion'), ('camera', 'Camera'), ('home', 'Home'), ('cars', 'Cars'), ('gaming', 'Gaming'), ('audio', 'Audio'), ('bikes', 'Bikes'), ('watch', 'Watch'), ('books', 'Books')], max_length=100),
        ),
    ]
